### ISSUE TITLE
Direct edit change detection

### ISSUE THREAD

**Issue by jakiwar** [wobkenh/simplematcomponents#29]
Is there any way to do change detection in direct edit mode? It seems the edit event only fires when being in normal edit mode.

Maybe providing a callback for ngModelChange would be a way to solve it?

As in e.g. https://stackoverflow.com/questions/49436205/handle-model-change-in-angular-5-component-two-way-binding

**Comment by wobkenh** [comment]
Thank you for filing this issue. 
I do not know your particular use case as you have not stated what exactly you want to do, but I do believe to have found a solution that should work good in most cases and give you a lot of freedom:

I will introduce a new callback that you can specify in the form field that will allow you to listen for model changes when direct edit is active. The callback will be passed the new value, the current property of the element and the element itself (with element meaning the parent object, i.e. the model described by the row). You will have to update the element yourself when using this callback. This is intentional, as it allows you to prevent invalid changes (validation) or to map values when necessary (e.g. nested objects).

I will post another comment when I release the update.

**Comment by wobkenh** [comment]
I published version 3.4 of simplemattable with the feature mentioned above.

Have a look at the code of the first table of this example:
[https://simplex24.de/smc-demo/direct-edit](https://simplex24.de/smc-demo/direct-edit)

**Comment by jakiwar** [comment]
That was a quick update! My use-case is to display checkbox-selected rows in a separate table without the need to press some "Apply" button to trigger the update of the separate table. It is a sneaky way to re-use your component as a selector.

**Comment by wobkenh** [comment]
Okay so I would consider this issue closed now. If you have any more ideas or run into any more problems, feel free to open a new issue or to reopen this one.
