### ISSUE TITLE
getPage() doesn't have access to component scope, only the table scope.

### ISSUE THREAD

**Issue by plinkpaste** [wobkenh/simplematcomponents#32]
I'm trying to use `getPage` for backend pagination.

My code looks like this:

```typescript
getPage(pageIndex: number, pageSize: number): Observable<Organisation[]> {
    return this.organisationService.getOrganisationsPaged(this.context, pageIndex, pageSize);
}
```

This all looks fine, and follows along with your example documentation:

```typescript
getPage(offset: number, limit: number): Observable<TestData[]> {
  /*
    Note that normally you would just return an observable obtained from a service method,
    which talks to your backend to fetch the data, e.g.:
    return this.myService.get(offset, limit);
  */
...
```

However, the function does not have access to the main component scope. When I run this, I get the error `Cannot read property 'getOrganisationsPaged' of undefined` because in this function `this` refers to the `SimplemattableComponent`:

![image](https://user-images.githubusercontent.com/7480500/67403364-b535f080-f5a9-11e9-8dcc-2c6925aea435.png)

Unfortunately, in this state, retrieving data from an external source outside of this function scope will never work.

**Comment by wobkenh** [comment]
In Javascript, knowing what `this` refers to can be very tricky. In this case, the `this` refers to the method that is calling the `getPage` method, which is simplemattable. This is because your `getPage` method is saved to an attribute of simplemattable and then executed in the simplemattable context. 

Fortunately, you can change the `this` that should be used in a function using the `bind` method. In your case, you would have to bind your `this` when supplying your `getPage` to `smc-simplemattable`:

```html
<smc-simplemattable [...] [getPage]="getPage.bind(this)"></smc-simplemattable>
```
This is the approach I also use in my own projects. This is a pitfall that is not obvious. I will document it in the readme and the demo application.
