### ISSUE TITLE
withSelectFormField Default value

### ISSUE THREAD

**Issue by bolusarz** [wobkenh/simplematcomponents#5]
when i try to edit a column using withSelectFormField, how can i set the default value to the value there before editing

**Comment by wobkenh** [comment]
Since the select is bound to a property of your model, you can assign your default value in the model and it will be displayed. Example:

If you allow adding of new elements and you want the new entry to have some default values, assign your default values to the object you return in the create-method (create-Input-Parameter), which is used to create a new instance of your model.

Applying a default value before editing of existing elements is currently not possible. I could add a new event though that fires before editing of an existing element is started. You could then apply your default values in reaction to that event. Is this what you are looking for?

**Comment by wobkenh** [comment]
Closing this since there have been no new questions.
