### ISSUE TITLE
Style MatRow?

### ISSUE THREAD

**Issue by alireza66617** [wobkenh/simplematcomponents#57]
How can I give a separate style to the mat-row on each page?

**Comment by wobkenh** [comment]
You can style rows the same way you can style individual column cells. Simplemattable has two input parameters `[ngRowClass]` and `ngRowStyle`, which each take a function which takes two arguments, `data: T` and  `dataList: T[]`. `data` is the object representing this row and `dataList` is a list of all objects.

This is also descriped [in the docs.](https://www.npmjs.com/package/simplemattable#row-customization)
I also added an example to the demo, but I currently have problems deploying the new version. So in the meantime, heres the example:

Model:
```typescript
export class ComplexTestData {
  constructor(
    public id: number,
    public value: number,
    public description: string,
    public data: TestData,
    public notes: string
  ) {}
}
```

Colums:
```typescript
    this.columnsRowCss = [
      new TableColumn<ComplexTestData, 'id'>('My ID - Color depends on id', 'id'),
      new TableColumn<ComplexTestData, 'description'>('Description', 'description'),
    ];
```

RowStyle Function:
```typescript
  rowNgStyle(datum: ComplexTestData) {
    return { 'background-color': 'rgb(0, ' + datum.id * 50 + ', 0)' };
  }
```

HTML:
```html
          <smc-simplemattable [data]="dataCustomCss" [columns]="columnsRowCss"
                              [rowNgStyle]="rowNgStyle"></smc-simplemattable>
```

Since you specifically asked for a separate style for each page... You can listen to the page event using the `page` output parameter of simplemattable and use this state to determine the styling in your `rowNgStyle` function or class in your `rowNgClass` function. Note that if you access the state of your component (using `this`) in your `rowNgStyle` function, you will have to pass the function as `rowNgStyle.bind(this)` since otherwise `this` would be simplemattable and not your component.

Hope this helps. If you have any more problems or questions, feel free to ask.

**Comment by wobkenh** [comment]
Btw, the deployment was fixed.
You can now also look at the [second example in the custom css demo here.](https://smc-demo.simplex24.de/custom-css)
